patchkit-net/patchkit-patcher-unity

.gitignore
src/Assets/Editor/Tests.meta
src/Assets/Editor/Tests/ChunkedFileTest.cs
src/Assets/Editor/Tests/ChunkedFileTest.cs.meta
src/Assets/Scripts/Patcher/ChunkedFile.cs
src/Assets/Scripts/Patcher/ChunkedFile.cs.meta
src/Assets/Scripts/Patcher/Patcher.cs
src/Assets/Scripts/Web/HttpDownloader.cs

Retry download after 10 seconds if wrong content size and .gitignore entries

---

Assets/PatchKit Patcher/Scripts/AppUpdater/Commands/InstallContentCommand.cs
CHANGELOG.md

http://redmine.patchkit.net/issues/588

Move files after install instead of copy

---

Assets/PatchKit Patcher/Scripts/AppUpdater/AppUpdater.cs
Assets/PatchKit Patcher/Scripts/AppUpdater/AppUpdaterContentStrategy.cs
Assets/PatchKit Patcher/Scripts/AppUpdater/AppUpdaterDiffStrategy.cs
Assets/PatchKit Patcher/Scripts/AppUpdater/AppUpdaterEmptyStrategy.cs
Assets/PatchKit Patcher/Scripts/AppUpdater/AppUpdaterStrategyResolver.cs
Assets/PatchKit Patcher/Scripts/AppUpdater/IAppUpdaterStrategy.cs
Assets/PatchKit Patcher/Scripts/AppUpdater/IAppUpdaterStrategyResolver.cs
Assets/PatchKit Patcher/Scripts/Patcher.cs

All editor tests passed.
development platform: Windows.

Feature #641 added fallback to strategy

---

Assets/PatchKit Patcher/Scripts/AppData/Local/Pack1Unarchiver.cs
Assets/PatchKit Patcher/Scripts/AppUpdater/AppUpdater.cs
Assets/PatchKit Patcher/Scripts/AppUpdater/Commands/InstallDiffCommand.cs
CHANGELOG.md

All editor tests passed.
Development platform: Windows.

Bugfix #714: Added suffix to unpacked files by diff strategy

---

Assets/PatchKit Patcher/Scripts/Patcher.cs

Development platform: Windows
All editor tests passed

Bugfix #559: "Uknown error" on no internet connection

---

Assets/PatchKit Patcher/Scripts/AppData/Remote/Downloaders/ChunkedHttpDownloader.cs

Made this to handle timeouts reported by downloader (this is another
case of timeouts for some reason).
I'm not sure if this won't catch too much, but it can actually be good.

ChunkedHttpDownloader: Handle WebException

---

Assets/Editor/BuildScript.cs
Assets/PatchKit Patcher/Editor/CustomBuilding.cs
Assets/PatchKit Patcher/Editor/PatcherManifestCreator.cs
Assets/PatchKit Patcher/Editor/ScreenSizeCorrection.cs
Assets/PatchKit Patcher/Scripts/UI/BorderlessWindow.cs
CHANGELOG.md

1. [x] Changelog entry
2. [x] Review requested
3. [x] `Version.cs` update - if required

Saving the screensize file in correct path

---

README.md

1. [ ] PR associated with Redmine issue (if applicable) **N/A**
2. [ ] Changelog entry with id of Redmine issue **N/A**
3. [ ] `Version.cs` up to date **N/A**
4. [x] Review requested

Starting the patcher without the launcher

---

Assets/PatchKit Patcher/Scripts/AppUpdater/Status/DownloadStatus.cs

3. [x] `Version.cs` up to date
4. [x] Review requested

#1124 Fix download speed calculation

---

Assets/PatchKit Patcher/Scripts/AppUpdater/Commands/RepairFilesCommand.cs
CHANGELOG.md

3. [x] `Version.cs` up to date
4. [x] Review requested

#1177 - Change repair status messages

---

Assets/PatchKit Patcher/Scripts/AppData/Local/LimitedStream.cs
Assets/PatchKit Patcher/Scripts/AppData/Local/Pack1Unarchiver.cs
Assets/PatchKit Patcher/Scripts/AppData/Local/ThreadBufferedStream.cs
Assets/PatchKit Patcher/Scripts/AppData/Local/ThreadBufferedStream.cs.meta
Assets/PatchKit Patcher/Scripts/Version.cs
CHANGELOG.md

3. [x] Created TODO for applying this change into 4.x.x line (if applicable)

3.13.0 Release

---

Assets/PatchKit Patcher/Scripts/AppUpdater/AppUpdater.cs
CHANGELOG.md

Fixed #1273

---

Assets/PatchKit Patcher/Scripts/PatcherError.cs

1. [ ] PR associated with Redmine issue (if applicable)
2. [ ] Changelog entry with id of Redmine issue
4. [ ] `Version.cs` up to date
5. [ ] Review requested

v3.14.0.0 hotfix

---

Assets/PatchKit Patcher/Scripts/AppUpdater/Commands/RepairFilesCommand.cs
CHANGELOG.md

3. [x] Created TODO for applying this change into 4.x.x line (if applicable)

Repairing files placed at long path (#1369)

---

Assets/PatchKit Patcher/Scripts/Api/Models/Main/AppDiffSummary.cs
Assets/PatchKit Patcher/Scripts/AppUpdater/Commands/InstallDiffCommand.cs
CHANGELOG.md

3. [x] Created TODO for applying this change into 4.x.x line (if applicable)

Skip unchanged files while patching (#944)

---

Assets/PatchKit Patcher/Scripts/Patcher.cs
CHANGELOG.md

Set process priority to Low (#1375)

---

Assets/PatchKit Patcher/Scripts/AppData/Local/BaseWritableDirectory.cs
CHANGELOG.md

4. [ ] `Version.cs` up to date

Fix recreating download directory (#1360)

---

Assets/PatchKit Patcher/Scripts/UI/Changelog/ChangelogList.cs
CHANGELOG.md

Cache app changelog (#1361)

---

Assets/PatchKit Patcher/Patcher_Multiple_Start_Buttons.unity
Assets/PatchKit Patcher/Patcher_Multiple_Start_Buttons.unity.meta
Assets/PatchKit Patcher/Scripts/AppStarter.cs
Assets/PatchKit Patcher/Scripts/AppUpdater/Commands/InstallDiffCommand.cs
Assets/PatchKit Patcher/Scripts/Patcher.cs
Assets/PatchKit Patcher/Scripts/UI/MessagePanel.cs
Assets/PatchKit Patcher/Scripts/UI/StartAppButton.cs
Assets/PatchKit Patcher/Scripts/UI/StartAppButton.cs.meta
Assets/PatchKit Patcher/Scripts/Version.cs
CHANGELOG.md

3. [x] Created TODO for applying this change into 4.x.x line (if applicable)

Merge 3.17.1.0 to master

---

Assets/PatchKit Patcher/Patcher.unity
Assets/PatchKit Patcher/Scripts/Patcher.cs

To 94987833c3b51565ce7bf85e9a747571
1. [ ] PR associated with Redmine issue (if applicable)
2. [ ] Changelog entry with id of Redmine issue
4. [ ] `Version.cs` up to date
5. [ ] Review requested

Change default app secret

---

Assets/PatchKit Patcher/Scripts/Debug/DebugMenu.cs

Fix v3.17.5.0-rc1

---

Assets/Editor/Tests/Pack1UnarchiverTest.cs
Assets/Editor/Tests/UnarchiverTest.cs
Assets/PatchKit Patcher/Scripts/AppData/Local/MapHashExtractedFiles.cs
Assets/PatchKit Patcher/Scripts/AppData/Local/MapHashExtractedFiles.cs.meta
Assets/PatchKit Patcher/Scripts/AppData/Local/Pack1Meta.cs
Assets/PatchKit Patcher/Scripts/AppData/Local/Pack1Unarchiver.cs
Assets/PatchKit Patcher/Scripts/AppData/Local/ZipUnarchiver.cs
Assets/PatchKit Patcher/Scripts/AppUpdater/AppUpdaterContentStrategy.cs
Assets/PatchKit Patcher/Scripts/AppUpdater/AppUpdaterDiffStrategy.cs
Assets/PatchKit Patcher/Scripts/AppUpdater/Commands/AppUpdaterCommandFactory.cs
Assets/PatchKit Patcher/Scripts/AppUpdater/Commands/CheckPathLengthCommand.cs
Assets/PatchKit Patcher/Scripts/AppUpdater/Commands/CheckPathLengthCommand.cs.meta
Assets/PatchKit Patcher/Scripts/AppUpdater/Commands/FilePathTooLongException.cs
Assets/PatchKit Patcher/Scripts/AppUpdater/Commands/FilePathTooLongException.cs.meta
Assets/PatchKit Patcher/Scripts/AppUpdater/Commands/ICheckPathLengthCommand.cs
Assets/PatchKit Patcher/Scripts/AppUpdater/Commands/ICheckPathLengthCommand.cs.meta
Assets/PatchKit Patcher/Scripts/AppUpdater/Commands/InstallContentCommand.cs
Assets/PatchKit Patcher/Scripts/AppUpdater/Commands/InstallDiffCommand.cs
Assets/PatchKit Patcher/Scripts/AppUpdater/Commands/RepairFilesCommand.cs
Assets/PatchKit Patcher/Scripts/Patcher.cs
Assets/PatchKit Patcher/Scripts/PatcherError.cs
Assets/PatchKit Patcher/Scripts/Version.cs
Assets/Resources.meta
CHANGELOG.md

Shortening the file path for unpacking
